export const SETSELECTTEMPLATE = "SELECTTEMPLATE";
export const ADDSELECTTEMPLATE = "ADDTEMPLATE";
export const SETPERSONALINFO = "ADDPERSONALINFO";
export const ADDEXPERIENCE = "ADDEXPERIENCE";
export const ADDEDUCATION = "ADDEDUCATION";
export const ADDKEYSKILLS = "ADDKEYSKILLS";
export const ADDPREVIEW = "ADDPREVIEW";
